apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatch-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dispatch-service
  template:
    metadata:
      labels:
        app: dispatch-service
    spec:
      containers:
        - name: dispatch-service
          image: greffnoah/dispatch-service:IMAGE_TAG
          ports:
            - containerPort: 80
          env:
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dispatch-secrets
                  key: rabbitmq-password
            - name: RABBITMQ_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: dispatch-secrets
                  key: rabbitmq-hostname
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: dispatch-secrets
                  key: rabbitmq-username
---
apiVersion: v1
kind: Service
metadata:
  name: dispatch-service-service
spec:
  selector:
    app: dispatch-service
  ports:
    - port: 80
