name: Deploy to Amazon EKS

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: eu-north-1

            - name: Configure kubectl
              uses: dawidd6/action-kubectl@v1.2.1
              with:
                  version: '1.22.0'
                  kubectl_version: 'latest'

            - name: Deploy to EKS
              run: |
                  kubectl apply -f ./k8s/manifests/
