name: Release CI Pipeline

on:
  release:
    types:
      - created

jobs:
  regression:
    runs-on: ubuntu-latest

    steps:
      - name: Run Cucumber Regression
        uses: greffgreff/run-java-tests-action@1.0
        with:
          repo: https://github.com/uniclip-io/test-suite.git
          branch: master

  docker:
    needs: regression

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: greffnoah/dispatch-service
          tags: ${{ github.ref_name }}
          registry: docker.io
          username: greffnoah
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

  deploy:
    needs: docker

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate kube configuration
        run: |
          mkdir ~/.kube
          touch ~/.kube/config
          echo "${{ secrets.AKS_CONTEXT }}" >> ~/.kube/config

      - name: Deploy application
        run: |
          sed -e 's|IMAGE_TAG|${{ github.ref_name }}|g' .k8s/deployment.yml | kubectl apply -f -

      - name: Restart pod
        run: kubectl rollout restart deploy dispatch-service
