name: Release CI Pipeline

on:
  release:
    types:
      - created

jobs:
  regression:
    runs-on: ubuntu-latest

    steps:
      - name: Run Cucumber Regression
        uses: greffgreff/run-java-tests-action@1.0
        with:
          repo: https://github.com/uniclip-io/test-suite.git
          branch: master

  aws:
    needs: regression

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push Image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: uniclip/dispatch-service
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Stop old task
        run: |
          TASK_ARN=$(aws ecs list-tasks --cluster ${{ secrets.AWS_CLUSTER }} --service-name ${{ secrets.AWS_SERVICE }} --desired-status RUNNING --query 'taskArns[0]' --output text)
          if [ ! -z "$TASK_ARN" ]; then
            echo $TASK_ARN 
            aws ecs stop-task --task $TASK_ARN --cluster ${{ secrets.AWS_CLUSTER }}
          fi

      - name: Run new task
        run: |
          aws ecs update-service --cluster ${{ secrets.AWS_CLUSTER }} --service ${{ secrets.AWS_SERVICE }} --force-new-deployment --task-definition DispatchService
